### ISSUE TITLE
打开失败

### ISSUE THREAD

**Issue by Altman29** [XuanRanDev/Auto-ShiXiBeiAn#11]
职校家园打卡失败,具体错误信息：HTTPConnectionPool(host='sxbaapp.zcj.jyt.henan.gov.cn', port=80): Max retries exceeded with url: /interface/token.ashx (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 110] Connection timed out'))

**Comment by XuanRanDev** [comment]
链接服务器超时，手动运行下action，此错误出现率不高，下个版本优化
