### ISSUE TITLE
有交流群一类的吗？

### ISSUE THREAD

**Issue by hh233330** [XuanRanDev/Auto-ShiXiBeiAn#17]

**Comment by XuanRanDev** [comment]
没有




XuanRan
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XuanRanDev/Auto-ShiXiBeiAn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月12日(星期一) 晚上10:16
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[XuanRanDev/Auto-ShiXiBeiAn] 有交流群一类的吗？ (Issue #17)

**Comment by hh233330** [comment]
好吧，要开始用了怕那天看的不及时不能用了忘记打所以问问😂

**Comment by XuanRanDev** [comment]
已经稳了半年多了，一般不会有什么问题

**Comment by hh233330** [comment]
好的好的，感谢感谢
