### ISSUE TITLE
打卡失败

### ISSUE THREAD

**Issue by Zoe-create** [XuanRanDev/Auto-ShiXiBeiAn#7]
<img width="248" alt="image" src="https://user-images.githubusercontent.com/78200235/213117751-3fcab52d-5c28-4933-a3ac-1a33454d9b46.png">
大佬，今天失效了吗
<img width="402" alt="image" src="https://user-images.githubusercontent.com/78200235/213117832-01099ced-4213-4fb6-b162-579b321f543e.png">

**Comment by XuanRanDev** [comment]
没用新版配置文件，使用新版本的配置就好了

**Comment by Zoe-create** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by Zoe-create** [comment]
好的，感谢

**Comment by 2015763971** [comment]
职校家园打卡失败,具体错误信息：HTTPConnectionPool(host='sxbaapp.zcj.jyt.henan.gov.cn', port=80): Max retries exceeded with url: /interface/token.ashx (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 110] Connection timed out'))  .............

**Comment by XuanRanDev** [comment]
> 职校家园打卡失败,具体错误信息：HTTPConnectionPool(host='sxbaapp.zcj.jyt.henan.gov.cn', port=80): Max retries exceeded with url: /interface/token.ashx (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 110] Connection timed out'))  .............

网络问题，重新运行下就好了，这错误出现率不高，下版本优化下
