### ISSUE TITLE
打开失败

### ISSUE THREAD

**Issue by Altman29** [XuanRanDev/Auto-ShiXiBeiAn#8]
职校家园打卡失败，错误原因：'randomLocation'
坐标小数点后六位，地址与坐标相符。

**Comment by XuanRanDev** [comment]
使用新版配置文件

**Comment by Altman29** [comment]
> 使用新版配置文件

请问哪里可以获取新版配置文件?

**Comment by XuanRanDev** [comment]
> > 使用新版配置文件
> 
> 请问哪里可以获取新版配置文件?

readme里面有
