### ISSUE TITLE
错误原因：Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Altman29** [XuanRanDev/Auto-ShiXiBeiAn#9]
已加载用户 xxx 即将开始打卡
xxx 打卡成功！
职校家园打卡失败，错误原因：Expecting value: line 1 column 1 (char 0)
推送消息提醒成功！

**Comment by XuanRanDev** [comment]
既然能打卡成功后面提示的打卡失败就先不用关，概率出现，暂时还没定位到问题（因为压根没研究）

**Comment by Altman29** [comment]
好的  还是十分感谢~~~
